# Site settings
title: 'Создаю мобильные приложения для iOS/Android'
description: '2 нативных мобильных приложения на лучших условиях: <br>- Если найдется конкурирующее предложение, я дам условия лучше.'
url: 'https://rakhimyan.ru/'
baseurl: 
google_analytics: 'UA-105772480-3'
disqus_shortname: 'rakhimyan'

author:
  name: 'Rakhimyan'
  email: rahimtoy@gmail.com
  twitter_username: rakhimyan
  facebook_username: rakhimyan
  github_username: RakhimyanTim
  linkedin_username: rakhimyan

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
